image: python:latest

before_script:
  - python --version
  - pip install -r requirements.txt

stages:
  - sync
  - lint

mirror-check:
  stage: sync
  script:
    - eval `ssh-agent -s`
    - echo "${SSH_PRIVATE_KEY}" | tr -d '\r' | ssh-add - > /dev/null
    - mkdir -p ~/.ssh && chmod 700 ~/.ssh
    - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
    - git config --global user.name  "Riccardo"
    - git config --global user.email "rgall@sertiscorp.com"
    - git fetch && git checkout develop
    - git remote add upstream https://github.com/gasgallo/mirror-test.git
    - git pull upstream develop
    - git remote rm origin && git remote add origin git@gitlab.com:rgall/mr-playground.git
    - git push origin HEAD

flake8:
  stage: lint
  script:
  - flake8 --max-line-length=120 *.py

